name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [vs17, vs18]

    steps:
      - uses: actions/checkout@v4

      - name: Configure (Static)
        run: cmake --preset ${{ matrix.preset }}

      - name: Build Static Debug
        run: cmake --build --preset ${{ matrix.preset }}-debug

      - name: Build Static Release
        run: cmake --build --preset ${{ matrix.preset }}-release

      - name: Package Static
        run: cpack --preset ${{ matrix.preset }}-zip

      - name: Configure (Shared)
        run: cmake --preset ${{ matrix.preset }}-shared

      - name: Build Shared Debug
        run: cmake --build --preset ${{ matrix.preset }}-shared-debug

      - name: Build Shared Release
        run: cmake --build --preset ${{ matrix.preset }}-shared-release

      - name: Package Shared
        run: cpack --preset ${{ matrix.preset }}-shared-zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/build/${{ matrix.preset }}/*.zip
            out/build/${{ matrix.preset }}-shared/*.zip
