name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [vs17]
        variant: [static, shared]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}-${{ matrix.variant }}

      - name: Build Debug
        run: cmake --build --preset ${{ matrix.preset }}-${{ matrix.variant }}-debug

      - name: Build Release
        run: cmake --build --preset ${{ matrix.preset }}-${{ matrix.variant }}-release

      - name: Package
        run: cpack --preset ${{ matrix.preset }}-${{ matrix.variant }}-zip

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/build/${{ matrix.preset }}-${{ matrix.variant }}/*.zip
